#!/bin/bash

for temp in 270 275 280 285 290 295 300; do

    root=figure/11um_$temp
    rm -f $root
    echo "Running figure"
    
    for uw in 0.0 0.25 0.5 0.75 1.0 1.25 1.5 1.75 2.0 2.25 2.5 2.75 3.0 3.25 3.5 3.75 4.0; do

        echo "
         &INPUT
           wlinf=11
           wlsup=11
           idatm=6
           alat=39
           alon=-77
           sza=95      !solar zenith angle: below horizon, nighttime
           isalb=0     !surface albedo: uniform, set by albcon
           albcon=0.05    !manually set albedo (isalb=0)
           uw = $uw
           btemp = $temp
           zout=0,100
           iout=1
         /" > INPUT

    ./sbdart >> $root

    done
done
