#!/bin/bash

for temp in 270 275 280 285 290 295 300; do

    root=figure/11um_$temp
    rm -f $root
    echo "Running figure"
    
    for uw in 0.0 0.25 0.5 0.75 1.0 1.25 1.5 1.75 2.0 2.25 2.5 2.75 3.0 3.25 3.5 3.75 4.0; do

        echo "
         &INPUT
           wlinf=11    !Lower WL limit: micrometers
           wlsup=11    !Upper WL limit: micrometers
           idatm=6     !US standard atmosphere (default)
           alat=41     !location: Georges Bank
           alon=-68
           sza=95         !solar zenith angle: below horizon, nighttime
           isalb=0        !surface albedo: uniform, set by albcon
           albcon=0.1    !manually set albedo (isalb=0)
           uw = $uw       !variable precipitable water
           btemp = $temp  !variable skin surface temperature
           zout=0,100     !bottom and top of altitude
           iout=1         !type of output
         /" > INPUT

    ./sbdart >> $root

    done
done
