#!/bin/bash

root=profile/profile_LWIR
rm -f $root
echo "Running profile"

echo "
    &INPUT
       wlinf=11,      !Lower WL limit: micrometers
       wlsup=11,      !Upper WL limit: micrometers
    
       idatm=6,        !atmosphere: 6 is US standard
       nf=3,           !use the MODTRAN3 solar spectrum

       ZGRID1=.5       !Resolution at bottom of the grid (km)
       ZGRID2=20       !Maximum step size at top of the grid (km)
       NGRID=60        !Number of height steps
    
       sza=120         !solar zenith angle: below horizon, nighttime
       alat=41,        !latitude on Earth
       alon=-68,       !longitude on Earth
    
       zout=0,100      !bottom and top of altitude
       iout=7
/" > INPUT

./sbdart >> $root