#!/bin/bash

root=profile/profile_LWIR
rm -f $root
echo "Running profile"

echo "
    &INPUT
       wlinf=11,      !Lower WL limit: micrometers
       wlsup=11,      !Upper WL limit: micrometers
    
       idatm=6,        !atmosphere: 6 is US standard
       nf=0,           !use the MODTRAN3 solar spectrum
       uo3=0,       !ozone set to zero (US atms usually has ozone)

       XCH4=0        !CH4 causes minor emission and BTD higher in the atmosphere
       XN2O=0        !N20 causes emission and BTD higher in the atmosphere

       ZGRID1=.25,      !Resolution at bottom of the grid (km)
       ZGRID2=20,       !Maximum step size at top of the grid (km)
       NGRID=60,        !Number of height steps
    
       sza=120,         !solar zenith angle: below horizon, nighttime
       alat=41,        !latitude on Earth
       alon=-68,       !longitude on Earth
    
       zout=0,100      !bottom and top of altitude
       iout=7
/" > INPUT

./sbdart >> $root